services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_DB: gestao_img
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    user: "999:999"

  app1-cadastro:
    build: ./app1-cadastro
    ports:
      - "5001:5001"
    volumes:
      - ./app1-cadastro:/app
    environment:
      - POSTGRES_DB=gestao_img
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=postgres
    depends_on:
      - postgres
    networks:
      - app-network

  app2-webhook:
    build: ./app2-webhook
    ports:
      - "5002:5002"
    volumes:
      - ./app2-webhook:/app
    environment:
      - POSTGRES_DB=gestao_img
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=postgres
    depends_on:
      - postgres
    networks:
      - app-network

  visualization1:
    build: ./app3-visualizacao
    ports:
      - "8083:5003"
    environment:
      - DELAY=0
      - POSTGRES_DB=gestao_img
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=postgres
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-network

  visualization2:
    build: ./app3-visualizacao
    ports:
      - "8084:5003"
    environment:
      - DELAY=10
      - POSTGRES_DB=gestao_img
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=postgres
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-network

  visualization3:
    build: ./app3-visualizacao
    ports:
      - "8085:5003"
    environment:
      - DELAY=20
      - POSTGRES_DB=gestao_img
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=postgres
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-network

  visualization4:
    build: ./app3-visualizacao
    ports:
      - "8086:5003"
    environment:
      - DELAY=30
      - POSTGRES_DB=gestao_img
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=postgres
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-network

  visualization5:
    build: ./app3-visualizacao
    ports:
      - "8087:5003"
    environment:
      - DELAY=40
      - POSTGRES_DB=gestao_img
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=postgres
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-network

  visualization6:
    build: ./app3-visualizacao
    ports:
      - "8088:5003"
    environment:
      - DELAY=50
      - POSTGRES_DB=gestao_img
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=postgres
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  postgres_data: 